service:
  name: douban
  icon: http://img3.douban.com/pics/nav/lg_main_a7.png
  description: 豆瓣
  auth_type: oauth1
  auth_data:
    key: input your key here
    secret: input your secret here
    consumer_params:
      auth_site: http://www.douban.com
      access_site: http://api.douban.com
      request_token_path: /service/auth/request_token
      access_token_path: /service/auth/access_token
      authorize_path: /service/auth/authorize
      signature_method: HMAC-SHA1
      scheme: header
  helper: >
    def convert_douban_description(desc)
      { :desc => desc }
    end

    def post_douban(paramss)
      ret = %q{<?xml version='1.0' encoding='UTF-8'?><entry xmlns:ns0="http://www.w3.org/2005/Atom" xmlns:db="http://www.douban.com/xmlns/">}
      paramss.each do |k, v|
        ret += "<#{k}>#{v}</#{k}>"
      end
      ret += "</entry>"
    end

trigger:
- name: 个人信息
  description: 个人在豆瓣的更新信息
  http_type: direct
  http_method: get
  period: "0 */1 * * *"
  in_keys: [name]
  source: http://www.douban.com/feed/people/#{name}/interests
  out_keys: [title, level, tags, comment, link]
  content_to_hash: >
    parse_xml content, 'rss > channel > item' do |item|
      desc = (item / 'description').inner_text
      {
        :title => (item / 'title').inner_text,
        :level => grab_text(desc, /<p>推荐: (.*?)</m),
        :tags => grab_text(desc, /<p>标签: (.*?)</m),
        :comment => grab_text(desc, /<p>备注: (.*?)</m),
        :link => (item / 'link').inner_text,
        :published => Time.parse((item / 'pubDate').inner_text)
      }
    end

- name: 我说
  description: 获得我说的信息
  http_type: oauth
  http_method: get
  period: "*/10 * * * *"
  in_keys: [name]
  source: /people/#{name}/miniblog
  out_keys: [content, image_link, related_link]
  content_to_hash: >
    parse_xml content, 'feed > entry' do |entry|
      image = (entry / 'link[@rel="image"]')
      related = (entry / 'link[@rel="related"]')
      {
        :content => (entry / 'title').inner_text,
        :image_link => (image.length != 0) ? image.attr('href').value : '',
        :related_link => (related.length != 0) ? related.attr('href').value : '',
        :published => Time.parse((entry / 'published').inner_text)
      }
    end

action:
- name: 我说
  description: 在豆瓣说上发表一条我说
  http_type: oauth
  http_method: post
  in_keys: [content]
  target: /miniblog/saying
  header:
    Content-Type: application/atom+xml
  body: >
    post_douban :content => content.strip
