service:
  name: 新浪微博
  icon: http://www.sinaimg.cn/blog/developer/wiki/LOGO_64x64.png
  description: 大眼新浪微博
  auth_type: oauth1
  auth_data:
    key: input your key here
    secret: input your key here
    consumer_params:
      site: http://api.t.sina.com.cn
  helper:

trigger:
- name: 自己的微博
  description: 自己发布的微博
  http_type: oauth
  http_method: get
  period: "*/10 * * * *"
  in_keys: []
  source: /statuses/user_timeline.json
  out_keys: [text, in_reply_to_user, source]
  content_to_hash: >
    parse_json content do |item|
      {
        :text => item["text"],
        :in_reply_to_user => item["in_reply_to_screen_name"],
        :source => item["source"].gsub(/<.*?>/, ''),
        :published => Time.parse(item["created_at"])
      }
    end

action:
- name: 发布微博
  description: 发布一条微博
  http_type: oauth
  http_method: post
  in_keys: [status]
  target: /statuses/update.json
  body: >
    { :status => status.strip }

- name: 发布图片
  description: 发布一条带图片的微博
  http_type: oauth
  http_method: post
  in_keys: [status, media_url]
  target: /statuses/upload.json
  header:
    Content-Type: multipart/form-data, boundary=-----------RubyMultipartPost
  body: >
    media = open(media_url, 'rb')

    multipart :status => status.strip, :pic => UploadIO.new(media, 'image/jpeg', File.basename(media_url))
